# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9bc3baabb0e4c248bc01a1589c1fb3a9066dc46468b6b634695563f11b7f77afec1030492586fe83932ce4dbb14aa5490f117e438296e85cfc7661c4ec626291

test:
  secret_key_base: d33a562b09b0be83e2d71e86a79f666e69f0306c72851d61d2bd48f5159a35dc3343d9e01954620ae1ed95480ce4d360dfb4818f983f3225bf867cad2494a54a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
